# Generated by Django 6.0.7 on 2026-07-13 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom_api', '0002_docente_padre_nino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='especialidad',
            new_name='AreaEspecializada',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='cedula_profesional',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='nombre',
        ),
        migrations.AddField(
            model_name='docente',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave_admin', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('GradoAcademico', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id_terapeuta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='terapeutas/fotos/')),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('regimen_fiscal', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('enfoque', models.CharField(blank=True, max_length=100, null=True)),
                ('institucion_egreso', models.CharField(blank=True, max_length=150, null=True)),
                ('cedula_profesional', models.CharField(blank=True, max_length=20, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('idiomas', models.CharField(default='Español', max_length=100)),
                ('estatus', models.CharField(default='Pendiente', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terapeuta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terapeuta',
                'verbose_name_plural': 'Terapeutas',
            },
        ),
        migrations.AddField(
            model_name='nino',
            name='terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='boom_api.terapeuta'),
        ),
    ]
