# Generated by Django 6.0.7 on 2026-07-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom_api', '0003_rename_especialidad_docente_areaespecializada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('lectoescritura', 'Lectoescritura'), ('matematicas', 'Matemáticas'), ('habilidades_sociales', 'Habilidades sociales'), ('vida_diaria', 'Vida diaria')], max_length=30)),
                ('nivel_dificultad', models.PositiveSmallIntegerField()),
                ('instrucciones', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='actividades/audio/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actividades/imagenes/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
