# Generated by Django 6.0.7 on 2026-07-28 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom_api', '0004_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('lectura', 'Lectura'), ('atencion', 'Atención'), ('motora', 'Habilidades motoras')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='boom_api.nino')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='boom_api.padre')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='boom_api.preguntaevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='boom_api.evaluacioninicial')),
                ('opcion_elegida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boom_api.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boom_api.preguntaevaluacion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'pregunta'), name='una_respuesta_por_pregunta')],
            },
        ),
    ]
