# Generated by Django 6.0.7 on 2026-08-03 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom_api', '0004_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='boom_api.nino')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='boom_api.padre')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCognitivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.JSONField()),
                ('generado_en', models.DateTimeField(auto_now=True)),
                ('nino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cognitivo', to='boom_api.nino')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_texto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('lectura', 'Lectura'), ('atencion', 'Atención'), ('motora', 'Habilidades motoras')], max_length=20)),
                ('valor', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='boom_api.evaluacioninicial')),
            ],
        ),
    ]
