# Generated by Django 6.0.7 on 2026-08-04 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom_api', '0005_evaluacioninicial_perfilcognitivo_respuestanino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Evento', to='boom_api.nino')),
            ],
        ),
        migrations.CreateModel(
            name='SesionNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('actividades_completadas', models.PositiveIntegerField(default=0)),
                ('tiempo_total_segundos', models.PositiveIntegerField(default=0)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='boom_api.nino')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_registradas', to='boom_api.padre')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_segundos', models.PositiveIntegerField()),
                ('completada', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boom_api.actividad')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='boom_api.sesionnino')),
            ],
        ),
    ]
