# Generated by Django 6.0.7 on 2026-08-04 04:30

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom_api', '0006_evento_sesionnino_registroactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='curp_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='curp_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='clave_admin',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='rfc',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='telefono',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AlterField(
            model_name='docente',
            name='curp',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=18, null=True)),
        ),
        migrations.AlterField(
            model_name='docente',
            name='direccion',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AlterField(
            model_name='docente',
            name='rfc',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=13, null=True)),
        ),
        migrations.AlterField(
            model_name='docente',
            name='telefono',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True)),
        ),
        migrations.AlterField(
            model_name='padre',
            name='direccion',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AlterField(
            model_name='padre',
            name='telefono',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True)),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='curp',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=18, null=True)),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='direccion',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='rfc',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=13, null=True)),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='telefono',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True)),
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
